/*
 * Copyright 2026 The Lumenwilds contributors.
 * Licensed under the Apache License, Version 2.0.
 */
package com.jus144tice.lumenwilds.datagen;

import com.jus144tice.lumenwilds.Lumenwilds;
import com.jus144tice.lumenwilds.registry.ModItems;
import com.jus144tice.lumenwilds.util.ResourceLocationHelper;
import net.minecraft.data.PackOutput;
import net.minecraft.world.item.BlockItem;
import net.minecraft.world.item.Item;
import net.neoforged.neoforge.client.model.generators.ItemModelProvider;
import net.neoforged.neoforge.client.model.generators.ModelFile;
import net.neoforged.neoforge.common.data.ExistingFileHelper;

/**
 * Generates item models. Standalone items use {@code item/generated} (flat {@code item/<name>} texture).
 * Block items inherit their block model, except shapes whose inventory model has a different name:
 * fence/wall/button → {@code block/<name>_inventory}, trapdoor → {@code block/<name>_bottom}, and doors
 * (which have no block model) → a flat {@code item/<name>} texture.
 *
 * <p>Block-model parents are referenced with {@link ModelFile.UncheckedModelFile} so we don't trip the
 * {@code ExistingFileHelper} on models generated by {@link ModBlockStateProvider} in the same datagen run
 * (e.g. {@code *_inventory}), which it can't see across providers.</p>
 */
public class ModItemModelProvider extends ItemModelProvider {

    public ModItemModelProvider(PackOutput output, ExistingFileHelper existingFileHelper) {
        super(output, Lumenwilds.MOD_ID, existingFileHelper);
    }

    @Override
    protected void registerModels() {
        for (var entry : ModItems.ITEMS.getEntries()) {
            Item item = entry.get();
            String name = entry.getId().getPath();
            if (!(item instanceof BlockItem) || name.endsWith("_door") || name.endsWith("_pane")) {
                // item/generated, layer0 = item/<name>. Doors and panes render from a flat item texture.
                basicItem(item);
                continue;
            }
            String parent;
            if (name.endsWith("_fence") || name.endsWith("_wall") || name.endsWith("_button")) {
                parent = "block/" + name + "_inventory";
            } else if (name.endsWith("_trapdoor")) {
                parent = "block/" + name + "_bottom";
            } else {
                parent = "block/" + name;
            }
            getBuilder(name).parent(new ModelFile.UncheckedModelFile(ResourceLocationHelper.modLoc(parent)));
        }
    }
}
