/*
 * Copyright 2026 The Lumenwilds contributors.
 * Licensed under the Apache License, Version 2.0.
 */
package com.jus144tice.lumenwilds.datagen;

import com.jus144tice.lumenwilds.Lumenwilds;
import com.jus144tice.lumenwilds.registry.ModItems;
import com.jus144tice.lumenwilds.util.ResourceLocationHelper;
import net.minecraft.data.PackOutput;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.item.BlockItem;
import net.minecraft.world.item.Item;
import net.minecraft.world.level.block.AmethystClusterBlock;
import net.minecraft.world.level.block.BushBlock;
import net.neoforged.neoforge.client.model.generators.ItemModelProvider;
import net.neoforged.neoforge.client.model.generators.ModelFile;
import net.neoforged.neoforge.common.data.ExistingFileHelper;

/**
 * Generates item models. Standalone items (incl. boats) and doors/panes/signs use {@code item/generated}
 * with a flat {@code item/<name>} texture. Most block items inherit their generated {@code block/<name>}
 * model. The exceptions are the shapes whose block-state helper does NOT emit a usable inventory model:
 * fence/wall/button reuse the vanilla {@code minecraft:block/{fence,wall,button}_inventory} parents with
 * our base texture; trapdoors inherit their generated {@code block/<name>_bottom}.
 *
 * <p>Modded block-model parents use {@link ModelFile.UncheckedModelFile} so we don't trip the
 * {@code ExistingFileHelper} on models generated by {@link ModBlockStateProvider} in the same run.</p>
 */
public class ModItemModelProvider extends ItemModelProvider {

    public ModItemModelProvider(PackOutput output, ExistingFileHelper existingFileHelper) {
        super(output, Lumenwilds.MOD_ID, existingFileHelper);
    }

    @Override
    protected void registerModels() {
        for (var entry : ModItems.ITEMS.getEntries()) {
            Item item = entry.get();
            String name = entry.getId().getPath();

            // Spawn eggs use the vanilla template_spawn_egg model (hand-authored, no flat texture) — skip
            // them so datagen doesn't demand an item/<name>.png that doesn't (and shouldn't) exist.
            if (item instanceof net.neoforged.neoforge.common.DeferredSpawnEggItem) {
                continue;
            }

            if (!(item instanceof BlockItem)
                    || name.equals("glowberry") // ItemNameBlockItem, but uses the berry icon (item/glowberry)
                    || name.endsWith("_door")
                    || name.endsWith("_pane")
                    || name.endsWith("_sign")
                    || name.endsWith("_chest")) { // chest = flat inventory icon (the block is BER-rendered)
                basicItem(item); // item/generated, layer0 = item/<name>
            } else if (item instanceof BlockItem bi
                    && (bi.getBlock() instanceof BushBlock || bi.getBlock() instanceof AmethystClusterBlock)) {
                // Flowers/ferns/crystal clusters render flat in the inventory, from their block texture.
                getBuilder(name).parent(mc("item/generated")).texture("layer0", tex(name));
            } else if (name.endsWith("_fence")) {
                getBuilder(name).parent(mc("block/fence_inventory")).texture("texture", baseTex(name));
            } else if (name.endsWith("_wall")) {
                getBuilder(name).parent(mc("block/wall_inventory")).texture("wall", baseTex(name));
            } else if (name.endsWith("_button")) {
                getBuilder(name).parent(mc("block/button_inventory")).texture("texture", baseTex(name));
            } else if (name.endsWith("_trapdoor")) {
                getBuilder(name)
                        .parent(new ModelFile.UncheckedModelFile(
                                ResourceLocationHelper.modLoc("block/" + name + "_bottom")));
            } else {
                getBuilder(name)
                        .parent(new ModelFile.UncheckedModelFile(ResourceLocationHelper.modLoc("block/" + name)));
            }
        }
    }

    private ModelFile mc(String path) {
        return new ModelFile.UncheckedModelFile(ResourceLocationHelper.mcLoc(path));
    }

    /** Base material texture for a fence/wall/button (mirrors {@link ModBlockStateProvider#baseTex}). */
    private ResourceLocation tex(String id) {
        return ResourceLocationHelper.modLoc("block/" + id);
    }

    private ResourceLocation baseTex(String name) {
        if (name.startsWith("glowwood_")) {
            return tex("glowwood_planks");
        }
        if (name.startsWith("glowroot_")) {
            return tex("glowroot_planks");
        }
        String base = name;
        for (String suffix : new String[] {"_wall", "_fence", "_button"}) {
            if (base.endsWith(suffix)) {
                base = base.substring(0, base.length() - suffix.length());
                break;
            }
        }
        if (base.endsWith("_brick") || base.endsWith("_tile")) {
            base = base + "s";
        }
        return tex(base);
    }
}
